#### Always use underscore _ to connect

# proxy
proxy:
  local_port: 16379
  enable_mtls: false

# p2p config
p2p:
  enable: true
  service_discovery_id: "p2p_redis_proxy_service_test"
  service_command_topic: "p2p_redis_proxy_service_topic_test"
  service_discover_mode: "advertise" # advertise or announce

# remote redis config
redisdb:
#  type: cluster # cluster、node
  type: node # cluster、node
#  start_nodes: "192.168.2.250:8001,192.168.2.250:8002,192.168.2.250:8003"
#  start_nodes: "192.168.2.250:6379"
  start_nodes: "127.0.0.1:6379"
  conn_timeout: 5 # Unit: second
  conn_read_timeout: 1
  conn_write_timeout: 1
  conn_alive_timeout: 60
  conn_pool_size: 80 # Connection pool 0 indicates the short connection
  slave_operate_rate: 0 # Percentage of read traffic carried by slave nodes: 0-> Slave nodes do not carry any read traffic
  cluster_update_heartbeat: 30 # Heartbeat interval for cluster status update: Takes effect only when READ/write separation is enabled: minimum 5 seconds

pprof_debug:
  enable: true
  port: 16060

log:
  level: debug

# IP address whitelist restriction
ip_white_list:
  enable: true
  list:
    - "127.0.0.1"
    - "localhost"

# Caching, proxy caching
cache:
  enable: true
  max_items_size: 2048 #Maximum number of items stored in the Cache
  default_expiration: 5000 # Cache KV default expiration time (milliseconds)
  cleanup_interval: 120 #Cache memory clearing interval (unit: second)


# Monitoring configuration
monitor:
  hotkey:
    enable: false #Whether to enable hotkey monitoring
    monitor_job_interval: 10 # Monitoring task time round policy: Single sleep time (unit: second)
    monitor_job_lifetime: 20 # Monitoring task Time round policy: Duration of a monitoring task (unit: second)
    second_hot_threshold: 500 # Hotkey identification threshold. After monitoring, if the key processing capacity per second is higher than the threshold, the key is considered as a hotkey
    second_increase_threshold: 25000 #Command processing increase rate (unit: second) If the command processing increase rate is higher than the threshold, the middleware immediately enables hotkey monitoring
    lru_size: 64 #The maximum hotkey storage space is based on the LRU policy
    enable_cache: false #Whether to enable the middleware cache function
    max_cache_life_time: 200 #Maximum cache entry lifetime (unit: ms)
  bigkey:
    enable: false #Whether to enable bigkey monitoring
    key_max_bytes: 1024 #Maximum redis key length (byte)
    value_max_bytes: 10240 #Maximum redis Value length (byte)
    lru_size: 64 #Bigkey Specifies the maximum storage space. Storage is based on the LRU policy
    enable_cache: false #Whether to enable the middleware cache function
    max_cache_life_time: 200 #cache Maximum entry survival time (unit: ms)
  slowquery:
    enable: false #Whether to enable slowQuery monitoring
    slow_query_threshold: 100 # Slow query time limit （unit：ms）
    max_list_size: 32 #Slowquery Maximum storage space
    slow_query_ignore_cmd: [] # Slowly check ignored commands

# prometheus metrics
prometheus_exporter:
  address: ":19090"
  hotkey_exporter:
    record_limit: 32
    include_metrics: [ "hotkey.record", "hotkey.count" ]
  bigkey_exporter:
    record_limit: 32
    include_metrics: [ "bigkey.count", "bigkey.record", "bigkey.value_size_sum" ]
  slowquery_exporter:
    record_limit: 16
  runtime_exporter:
    enable: true
    enable_cpu: true
    enable_mem: true
    enable_gc: true

ignore_cmd:
  enable: false
  cmd_list: []